services:
  nginx:
    build: ./.nginx
    container_name: web-server-nginx
    ports:
      - 8080:${NGINX_PORT}
    volumes:
      - ./frontend/dist:/var/www/html
    networks:
      - appnet
    depends_on:
      - frontend